@ECHO off

SET PROJECTDIR=%cd%
SET DBGDIR=%PROJECTDIR%\build-dbg
SET RELDIR=%PROJECTDIR%\build-rel

IF "%1"=="clean" (
   IF EXIST %DBGDIR% RMDIR /S /Q %DBGDIR%
   IF EXIST %RELDIR% RMDIR /S /Q %RELDIR%
   GOTO :EOF
)

SET CC=cl.exe
SET CXX=cl.exe
IF NOT EXIST %DBGDIR% MKDIR %DBGDIR%
cmake -GNinja -B %DBGDIR% -DCMAKE_BUILD_TYPE=Debug -S %PROJECTDIR%
IF NOT EXIST %RELDIR% MKDIR %RELDIR%
cmake -GNinja -B %RELDIR% -DCMAKE_BUILD_TYPE=Release -S %PROJECTDIR%
