@ECHO off

SET PROJECTDIR=%cd%
SET BUILDDIR=%PROJECTDIR%\build

IF "%1"=="clean" (
   IF EXIST %BUILDDIR% RMDIR /S /Q %BUILDDIR%
   GOTO :EOF
)

SET CC=cl.exe
SET CXX=cl.exe

IF NOT EXIST %BUILDDIR% MKDIR %BUILDDIR%
cmake -GNinja -B %BUILDDIR% -S %PROJECTDIR%
